### ISSUE TITLE
How to include stack trace to the error like pkg/errors?

### ISSUE THREAD

**Issue by sunfmin** [jjeffery/errors#4]
I like to have the ability to have Keyvals context value for structure logging. I was wondering how to include stack trace?

**Comment by jjeffery** [comment]
@sunfmin Thanks for your interest. I agree that it would be useful to be able to access a stack trace, but have not implemented this feature yet. What you can do is use the [github.com/go-stack/stack](https://github.com/go-stack/stack) package to include the stack as a parameter in your error message.

```go
errors.New("this is my error message").With("stack", stack.Trace().TrimRuntime())
```
